### ISSUE TITLE
Weird filtering behavior

### ISSUE THREAD

**Issue by RobOK2050** [nothingislost/obsidian-bartender#16]
I am having strange filtering that seems to happen only when the search string reaches four characters. The strangest thing i have seen.

Search term, typing in a.... l.... e..... (not typing in the dots, but just pausing between letters), and the files with "**ale**x" and "t**ale**nt" correctly show up. then i continue to an "a", so I have "alea" as the filter term. At this point, the first "a" is ignored and words matching "lea" now showup. I have a ton of files with "**lea**dership" so my list goes from 5 files to like 30. But "leadership" should not match "alea".

**Comment by nothingislost** [comment]
This should be improved in 0.5.2
