### ISSUE TITLE
Drag & Drop Sorting Not Working

### ISSUE THREAD

**Issue by DraconicVision** [nothingislost/obsidian-bartender#22]
The sorting issue can be seen [here](https://drive.google.com/file/d/1rB-lbbdukGg6J3o9hp5ASO83X4Q3kaDk/view?usp=sharing).

Any clue what the issue might be? Diagnostic info is visible in the video. Any help would be appreciated!

Note: I'm a new Obsidian user so it's possible I could be missing something here.

**Comment by looneyapache** [comment]
Same issue here, It was working a few days back before update

**Comment by nothingislost** [comment]
Hmm, you may not be clicking and holding for long enough. Try clicking, holding the mouse button down, and not moving for a longer period of time before attempting to start the drag.

This delay is in place to prevent interfering with the ability to actually click the elements. You can customize the delay in the settings to whatever is most natural for you without causing click issues 
![image](https://user-images.githubusercontent.com/89109712/157292851-0445443a-b68e-42ef-8e00-770a1da8a388.png)

**Comment by looneyapache** [comment]
🙌
Yes, that was the problem (Layer 8) :)  !
Thank you!!!

**Comment by tomas-kucera** [comment]
Yes ... had the same ... seems like UX  issue. I am fine with it when knowing it and definitely it is not a high priority.

But maybe give a user a visual clue (cursor change) that the D&D op is ready to proceed. ;)

Otherwise ... GREAT, GREAT, GREAT!!!! Thanks for it!
