### ISSUE TITLE
Has never worked for me

### ISSUE THREAD

**Issue by favonicass** [nothingislost/obsidian-bartender#27]
I installed Bartender through BRAT and it hasn't worked. I've tried toggling off all other plugins, and still, unable to work.

In the screen recording, I try to toggle the button, and it still doesn't work. Please help

https://user-images.githubusercontent.com/106928983/172066562-b4c65de1-69e4-47e8-b65c-6a9da3b5c19c.mov

**Comment by Vaelek** [comment]
You are not holding long enough. Go into the plugin settings and lower the time you must long press the left button without moving first, or hold it longer before trying to drag. The default setting is way to high and unobvious imo.

**Comment by nothingislost** [comment]
Yes, agreed, the delay was annoying and not needed. The latest version removes the trigger delay when dragging file explorer items.
