### ISSUE TITLE
After latest update, can't open or close folders when custom sorting

### ISSUE THREAD

**Issue by jebeaudoin** [nothingislost/obsidian-bartender#28]
My version is 0.5.3 and I'm on the latest insider Obsidian release. Today, for the first time, I couldn't open or close folders when custom ordering was selected. If I change it to one of Obsidian's default orders (e.g. by file name ascending) I can open and close folders.

**Comment by Mara-Li** [comment]
EDIT : Last update fix everything for me ! Thanks you

**Comment by nothingislost** [comment]
This is the case even when the "drag to rearrange" button is disabled? Please make sure you leave that disabled unless you're actively moving items around.

**Comment by jebeaudoin** [comment]
How do you disable the "drag to rearrange" button? Right now, I have to disable the entire plugin if I want to reveal the contents of folders. But if I do that, I lose my ordering.

**Comment by akadormouse** [comment]
Currently, I can change the sort order of files at the base level of the vault.
I cannot change the sort order of files within a folder.
Nor can I change the sort order of folders.

**Comment by nothingislost** [comment]
> How do you disable the "drag to rearrange" button? Right now, I have to disable the entire plugin if I want to reveal the contents of folders. But if I do that, I lose my ordering.

There's a button? 
![image](https://user-images.githubusercontent.com/89109712/174652763-382e21fd-137a-4ace-9d43-dd71342bd2f0.png)

**Comment by jebeaudoin** [comment]
If that was sarcasm, it's unnecessary.  Clicking on the button — which I tried even before filing the original bug report — does nothing. I'm attaching a 20-sec video of what I'm seeing. You'll observe that: 
1. The video starts with standard folder name alpha order, and the folders open. 
2. I then select custom order from the sort button (⇵), the "drag to rearrange button" (▤)appears and the folders are now arranged in my custom order. But they can not be opened.
3. I attempt to click on "drag to rearrange button" (▤) and nothing happens. The button is unresponsive. Is that the expected behavior?

With respect,
Jack

https://user-images.githubusercontent.com/10992411/174656420-3915e7a1-d442-4331-a867-040e5173128b.mov

**Comment by nothingislost** [comment]
> If that was sarcasm, it's unnecessary. Clicking on the button — which I tried even before filing the original bug report — does nothing.

I seem to have misunderstood your issue with the button. I was under the impression that you didn't know where the button was. Your theme appears to be making the fact that the button is activated very difficult to discern. Note how it looks in the default theme when activated: 
![image](https://user-images.githubusercontent.com/89109712/174689127-943ff72d-c292-40d0-aeb2-ebbaceea0e1c.png)

Regardless, it appears the button isn't directly related to your issue. Videos like this help considerably in understanding what you're seeing. That being said, I can't replicate this at all. Can you please try a new/sandbox vault with Bartender installed and see if you see the same behavior?

Also, just double checking, have you restarted Obsidian since upgrading to 0.5.4? Unfortunately due to the changed Bartender makes, you must restart Obsidian after each plugin upgrade.

**Comment by jebeaudoin** [comment]
These are very helpful. I'll follow your directions and see if I can narrow in on the issue. My hunch is that it's an unfortunate interaction with another plugin, but we'll see. Many thanks!

**Comment by corinnekaryiu** [comment]
> These are very helpful. I'll follow your directions and see if I can narrow in on the issue. My hunch is that it's an unfortunate interaction with another plugin, but we'll see. Many thanks!

Hi @jebeaudoin, I'm having the same exact issue. I have a lot of plugins, so I'll try looking into what is causing it, but it may take some time.  Please do let me know if you figure it out first!

**Comment by jebeaudoin** [comment]
Hey @corinnekaryiu,

So I've got a sandbox with no other plugins and Bartender is working as expected. That's the good news. So the bad news is that it's interacting with another plugin. Like you, I've got more than a few, so it will take me some time to see if I can isolate it. I'll report back in if I can find it.

**Comment by jebeaudoin** [comment]
Well, faster than I thought. If I turn off cMenu, bartender works as expected. @corinnekaryiu -- are you using cMenu?

@nothingislost - Has anyone else reported issues using cMenu? If that's the issue, what's the next step? I'm happy to put in the legwork to get this reconciled.

**Comment by nothingislost** [comment]
> Well, faster than I thought. If I turn off cMenu, bartender works as expected. @corinnekaryiu -- are you using cMenu?
> 
> @nothingislost - Has anyone else reported issues using cMenu? If that's the issue, what's the next step? I'm happy to put in the legwork to get this reconciled.

Thank you! I haven't seen any reports regarding cMenu but I can definitely replicate this with cMenu enabled. I should be able to fix this now that I know what's going on.

**Comment by corinnekaryiu** [comment]
@jebeaudoin Yes, thank you so much! I was using cMenu and have disabled it for now.

**Comment by nothingislost** [comment]
Please try https://github.com/nothingislost/obsidian-bartender/releases/tag/0.5.7

**Comment by jebeaudoin** [comment]
>> Updated Bartender to 0.5.7 in my sandbox vault. Closed and reopened vault. Enabled cMenu.
1. cMenu visible in main pane.
2. Bartender functions as expected.

Thanks for this quick fix!
