### ISSUE TITLE
File filter not working - suggestions

### ISSUE THREAD

**Issue by RobOK2050** [nothingislost/obsidian-bartender#30]
I have restarted obsitian and Bartender. I type in words in the filter field and nothing is happening. Any thoughts? Have not restarted my Mac yet.

**Comment by nothingislost** [comment]
Filtering does seem to be broken as of 0.15.x. I haven't had a chance to look into what it will take to fix it but I will try and do that shortly.

**Comment by nothingislost** [comment]
Try out 0.5.5 and let me know how it goes https://github.com/nothingislost/obsidian-bartender/releases/tag/0.5.5

**Comment by RobOK2050** [comment]
I will tomorrow, thanks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
