### ISSUE TITLE
[Bug][Mobile] Can't scroll file explorer with custom sorting

### ISSUE THREAD

**Issue by Mara-Li** [nothingislost/obsidian-bartender#31]
I can't move any folder when custom sorting. When I try to scroll, it's like I long press on the file and move it. To repro : 
- Set custom sorting
- Disable the drag to rearrange
- Try to scroll to down of the explorer.

In place of scroll, the folder will be selected and move.

### Env 
- iOS and IpadOS 15.5
- Obsidian 1.2.2

**Comment by ColColonCleaner** [comment]
Confirmed this is affecting both mobile and desktop, running into it as well.

Mobile: Android 12, Samsung Galaxy S22 Ultra, Obsidian 1.2.2
PC: Windows 10, Obsidian 0.14.15

On PC I'm unable to drag a note to insert its link into another note, even with 'drag to rearrange' turned off. Turning off custom sorting removes the issue.

**Comment by Mara-Li** [comment]
I will create another issue for "dragging"

**Comment by nothingislost** [comment]
Please try https://github.com/nothingislost/obsidian-bartender/releases/tag/0.5.7

**Comment by Mara-Li** [comment]
Thanks ! Work like a charm with the update :)

**Comment by ColColonCleaner** [comment]
Confirmed both of my issues are now fixed on both mobile and PC. Thank you!
