### ISSUE TITLE
[BUG] Dragging in file doesn't work

### ISSUE THREAD

**Issue by Mara-Li** [nothingislost/obsidian-bartender#32]
In Obsidian 0.15.3 and Bartender 0.5.6, dragging file (any file, image, pdf or md for example) will "bug" and doesn't work. 

Note : The mouse icon will become and keep to be the "hand". 

Removing the custom sort fix the problem

(Maybe related to #31)

**Comment by nothingislost** [comment]
Please try https://github.com/nothingislost/obsidian-bartender/releases/tag/0.5.7

**Comment by Mara-Li** [comment]
Work like a charm n.n ! Thanks you
