### ISSUE TITLE
Stopped working in Obsidian v1

### ISSUE THREAD

**Issue by andrewcrook** [nothingislost/obsidian-bartender#37]
plugin has stopped working since updating to Obsidian v1.
I no longer see the icon to collapse toolbars.

**Comment by XMB-7** [comment]
Just reinstall this plugin, then you would find it still works.

**Comment by ChristinWhite** [comment]
Reinstalling did not fix that for me. On the sidebar ribbon the show/hide button still works and hides any buttons below it but I can't rearrange the buttons and set which are shown and which will be hidden.

**Comment by andrewcrook** [comment]
@XMB-7 

I reinstalled and it worked until I restarted obsidian then it stop working again.
I think there is a bug with the new theme system I noticed a lot of themes are now labelled legacy so something has changed.

**Comment by osman1963** [comment]
Try changing the sort order to 'custom'. This will show the plugin button. 
if it still doesn't work, try clicking the  the button on and off again
if this doesn't work, try disabling then enabling the plugin

**Comment by looneyapache** [comment]
Try holding down the mouse button for a longer period of time.
There is a delay setting

Folders also move immediately.

**Comment by andrewcrook** [comment]
> Try holding down the mouse button for a longer period of time. There is a delay setting Folders also move immediately.
> […](#)

@looneyapache

click on what when I restart I don't get the collapsible icons.
I swear this is a bug with the new templating system.

<img width="889" alt="image" src="https://user-images.githubusercontent.com/803618/198370309-9d122e66-5970-4443-8fa7-efdbeb4c274c.png">

<img width="45" alt="image" src="https://user-images.githubusercontent.com/803618/198370424-c3c6ae05-dd1e-4fc3-bf43-fedaf7141692.png">

**Comment by looneyapache** [comment]
On my Windows 10 laptop, the provided plugin performs well. I frequently
move files and folders with this plugin, and I've never experienced any
problems.(Even with latest release 1.03)

At the moment, it is all I could say.

**Comment by andrewcrook** [comment]
> On my Windows 10 laptop, the provided plugin performs well. I frequently move files and folders with this plugin, and I've never experienced any problems.(Even with latest release 1.03) At the moment, it is all I could say.
> […](#)

Thanks for trying

**Comment by andrewcrook** [comment]
I have found a solution 

I had to change themes around couple of times and restart.
I don't know if this forced a needed theme update or cleared some sort of theme cache.

Seems to be working fine now thanks all

**Comment by osman1963** [comment]
Great that your problem is solved @andrewcrook . I was just about to suggest using the default theme.  As a rule of thumb, the devs of Obsidian recommended using only updated themes.

**Comment by ChristinWhite** [comment]
I didn't change anything I could specifically point to but I flipped Bartender on again and it's working for me now!
