### ISSUE TITLE
manual sort not working -- even when Custom Sort is selected

### ISSUE THREAD

**Issue by bblais** [nothingislost/obsidian-bartender#39]
I was very excited for this plugin, and installed it (Obsidian v 1.03 on the Mac), chose Custom Sort on the menu on the top, and tried to rearrange files.  Nothing happened -- it was the same select file as before.  I feel I must be doing something basic wrong, but can't for the life of me figure it out.  Any info you need to help debug this issue?  Thanks!

**Comment by bblais** [comment]
FIXED.  The docs were not quite clear, but an answer on the forum had the solution.

https://forum.obsidian.md/t/file-explorer-custom-sort/1602/190

- Click the “Up-Down Arrow” and select “Custom”:
- Now you see “a hamburger” right to the “Up-Down Arrow”. Click it to highlight it (toggle it on).  It says "Drag to rearrange"
- Click and Move any file in the folder view to move position inside the same folder. This position is persisted.

**Comment by cuprousoxide** [comment]
Thanks! I wish this were documented
