### ISSUE TITLE
[Feature Request] Support for Hider Plugin when hiding icons

### ISSUE THREAD

**Issue by Obadiahcruz** [nothingislost/obsidian-bartender#4]
Hider plugin allows the left ribbon bar to be hovered on the bottom left corner instead of always visible like default. 

The hovering creates conflicts with the new hiding icons feature. 

Would be great to support hider plugin with your planned future releases

**Comment by nothingislost** [comment]
The hider plugin just hides the ribbon. Are you using Minimal or something? because the floating bar seems to be something minimal is doing.

**Comment by Obadiahcruz** [comment]
yea its minimal theme with the hider plugin using hide app ribbon settings.

it actually seems to work better with 0.2.0 but now the icon to hide the icons is a little hard on the eyes

<img width="515" alt="Screen Shot 2022-01-25 at 2 38 52 PM" src="https://user-images.githubusercontent.com/22825246/151071563-635bad1a-f41e-4d19-9363-af101930626a.png">

**Comment by Obadiahcruz** [comment]
actually with the new settings, i put 100 delay for applying the hiding and it works lol those are new

**Comment by nothingislost** [comment]
yeah, I plan on making the icon customizable. I still don't think it works properly when the orientation gets shifted like that. it doesn't seem to hide the correct icons for me.

**Comment by Obadiahcruz** [comment]
nice! 
and yea thats the other feature request that i had mentioned to include the order or settings help and vaults

**Comment by nothingislost** [comment]
Support for minimal's floating bar is in 0.3.0. Support for the settings icons will come later as I'm still thinking about how to best handle those.
