### ISSUE TITLE
File explorer (filename filter) is not working

### ISSUE THREAD

**Issue by RobOK2050** [nothingislost/obsidian-bartender#45]
Is it incompatible with new Obsidian releases?

**Comment by Xieleilab** [comment]
the same question encounterd, in obsidian v 1.2.7,File explorer (filename filter) is not working

**Comment by vlad-infra-admin** [comment]
I came to ask the same question. Did you guys find any alternatives?

**Comment by LakeishaKowalczyk** [comment]
+1

**Comment by RobOK2050** [comment]
Thanks @Aetherinox for adding in.... We are talking about one feature in particular where in the original tool bar you pick Files and then in the second tool bar you pick the search. This activates a File Filter where is shortens the list to only matching files. For reference, this for me replicates a function from nvAlt a markdown editor. It's super handy. But, not working in Bartender anymore. Can you check that function to clarify your post?

**Comment by nothingislost** [comment]
Try out the latest 0.5.8 version and let me know how it goes

**Comment by RobOK2050** [comment]
Yes! Thank you friend! Where can we make a donation or show appreciation?

**Comment by vlad-infra-admin** [comment]
> Try out the latest 0.5.8 version and let me know how it goes

Thank you it works, but it broke custom order. So now objects in alphabetical order. Plus button is not available after I restarted Obsidian

**Comment by vlad-infra-admin** [comment]
> Try out the latest 0.5.8 version and let me know how it goes

It is working perfectly!! Thank you very much, nothingislost for getting back to us!!!

**Comment by RobOK2050** [comment]
Not to bring bad news…. On the filter, if I type a word and then a space, the space is there but does not show up. Hard to explain. Let's say I put the word "farmer" then a space and start another word. The only thing that shows in the filter is the first word and characters stop showing up. I hope that makes sense.

**Comment by nothingislost** [comment]
> Not to bring bad news…. On the filter, if I type a word and then a space, the space is there but does not show up. Hard to explain. Let's say I put the word "farmer" then a space and start another word. The only thing that shows in the filter is the first word and characters stop showing up. I hope that makes sense.

Thanks for the heads up. I see the issue. Should have a fix for it today or tomorrow.

**Comment by nothingislost** [comment]
Should be fixed in 0.5.9

**Comment by RobOK2050** [comment]
That worked, thank you.
Is there any way to have Down Arrow go from the search field into the results?

**Comment by Aetherinox** [comment]
Filter is working great again.

**Comment by RobOK2050** [comment]
Thank you @nothingislost !!
