### ISSUE TITLE
[BUG] Can't move icon in sidebar tab bar [Windows11]

### ISSUE THREAD

**Issue by Mara-Li** [nothingislost/obsidian-bartender#5]
**Description**
I can't move icons from left/right sidebar tab bar.
This functionnality was added in the 0.2.0 version.

https://loom.com/share/41720ac37a904606bff91484c96dfc86

**Version** : 
- Obsidian version : 0.13.23
- Bartender : 0.3.1
- Windows 11

**Comment by nothingislost** [comment]
Hmm I can't replicate this. Have you tried restarting Obsidian? Are you pressing alt while clicking the tab bar icons? You also need to click and hold for a second before dragging so try holding alt, clicking, waiting just a second, and then drag.

**Comment by Mara-Li** [comment]
Ah ! I didn't know I need to press ALT !
It works as expected, sorry for the inconvenience :)
