### ISSUE TITLE
Stopped working after updating Obsidian to 1.6.2

### ISSUE THREAD

**Issue by looneyapache** [nothingislost/obsidian-bartender#59]
Stopped working after update :(.
I upgraded Obsidian from 1.5.x to 1.6.2 and Drag /Rearrange Menu items doesn't works anymore.
Please help!

![image](https://github.com/nothingislost/obsidian-bartender/assets/10562851/5cdf7253-add0-4886-b571-8338d5acce7c)

![c41fcf0511165421c4abcb096512e01f4f53e59c](https://github.com/nothingislost/obsidian-bartender/assets/10562851/57bf9daf-4db7-407d-8310-d7a3c355d97c)

**Comment by wildlesle** [comment]
me too. same issue.

**Comment by sumangliu** [comment]
same for me

**Comment by 91ma** [comment]
same for 1.6.3

**Comment by looneyapache** [comment]
Seems like there is solution but I am not developer so I just dont know as yet how to figure it out

https://github.com/Mara-Li/obsidian-bartender (Updated about 4-5 days back - about the same time Obsidian new release)

**Comment by Lepton-Lee** [comment]
> Seems like there is solution but I am not developer so I just dont know as yet how to figure it out
> 
> https://github.com/Mara-Li/obsidian-bartender (Updated about 4-5 days back - about the same time Obsidian new release)

it works

**Comment by looneyapache** [comment]
Plea

> > Seems like there is solution but I am not developer so I just dont know as yet how to figure it out
> > https://github.com/Mara-Li/obsidian-bartender (Updated about 4-5 days back - about the same time Obsidian new release)
> 
> it works

Please help , I still cannot get it working.
Thank you!

**Comment by Lepton-Lee** [comment]
> Plea
> 
> > > Seems like there is solution but I am not developer so I just dont know as yet how to figure it out
> > > https://github.com/Mara-Li/obsidian-bartender (Updated about 4-5 days back - about the same time Obsidian new release)
> > 
> > 
> > it works
> 
> Please help , I still cannot get it working. Thank you!

Just download and extract it : https://github.com/Mara-Li/obsidian-bartender/releases/download/0.5.12/obsidian-bartender.zip. Then you may need to reorder the folders in the root directory.

**Comment by looneyapache** [comment]
> > Seems like there is solution but I am not developer so I just dont know as yet how to figure it out
> > https://github.com/Mara-Li/obsidian-bartender (Updated about 4-5 days back - about the same time Obsidian new release)
> 
> it works

Issue Resolved by https://github.com/Mara-Li/obsidian-bartender

I am grateful for her help.
