### ISSUE TITLE
Where is main.js?

### ISSUE THREAD

**Issue by korm** [nothingislost/obsidian-bartender#6]
Instructions say to copy over main.js to .obsidian. 

There is no main.js.

**Comment by Mara-Li** [comment]
https://github.com/nothingislost/obsidian-bartender/releases
Here is the main.js

You can also use BRAT, that is a better way to test application (because there is auto update at obsidian startup)

**Comment by korm** [comment]
Yeh, BRAT is easier -- I added your plugin a few hours ago.  It's nice work.   Does what it says it does; which is something I've always wanted OBS to do.   Thanks for your work.
