### ISSUE TITLE
[Bug] File Names don't recover to their original name after displaying in the Filter Items

### ISSUE THREAD

**Issue by damiankorcz** [nothingislost/obsidian-bartender#8]
Hi @nothingislost,

Just spotted a bug with the Filter Items option. Any file that shows up in the search results keeps the augmented name with the folder structure prefixed even when you disable the Filter Items button.

Here is a GIF to help show what I mean: 
![Obsidian_2022-02-06_19-40-24](https://user-images.githubusercontent.com/7290097/152698466-4d1e172a-f1d7-4917-a696-e6ed25c94648.gif)

**Comment by nothingislost** [comment]
Hmm, my results reset when clicking that button... but I have seen this happen occasionally so I do recognize that it's a problem. I'll see if I can track it down.

**Comment by damiankorcz** [comment]
Yeah seems to be good on my end. Thank you!
