### ISSUE TITLE
File names not showing beyond 1 folder deep

### ISSUE THREAD

**Issue by RobOK2050** [nothingislost/obsidian-bartender#9]
On Mac OS. Have 3-4 levels of folder. Notably the first folder starts with an underscore, some programs thrown off by that.

_TextFiles
...... Health
............ Way of Eating       <-- files in this folder not being found

**Comment by nothingislost** [comment]
Yeah, this is a weird one. I can't pinpoint what exactly the problem is yet but for now it should work if you search for "Way of Eating" with quotes.

**Comment by nothingislost** [comment]
This should be better in 0.5.1

**Comment by RobOK2050** [comment]
When I type a single or double quote into filter, I immediately get a blank list. It searches on the quote itself.

My example above was not exactly correct, here is the actual path and a sample file name (but no file is being found, so its not the file name):

_TextFiles / Body and Soul / Health / Way of Eating.md

(I am on 0.5.0, will report back after next version)

_TextFiles

**Comment by RobOK2050** [comment]
I have another vault in which folders works fine. I think it is the Leading underscore. I would like to keep that if possible.

**Comment by RobOK2050** [comment]
I think this can be closed, I don't know if I should close it or you?
